language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: Gros3ZGeuAq3G/DecKwYOnPK2ZABvcRHgXHQD2j1ELgA8HXN7iQsh72xtACB1h/GBilVps7o5uJpfaT8QtmnuWWoQHDFRFEdIkvZhpCULCUpTcwCwI5skffqnirLZGkxxDxn2IBnaMFBxXTEzOQhIYamuOhME/lncRxaWxk71lJDMywtIEA0Z3ZwNVcuzjEQLbK9iTzBr+aFEGDfK6Ut48ww5UG8zzlOeemWtpXJUlm+ynAH3aaS1S5gsx0GaazbRKp+7m58MQkmw6jLSHTJaRQ5r3c/hbSEBMojZt5d9It4o9Sfg0WO/bNoWf0miO5sWiC7diVN6vGi3uHT4iwiZzhU+FSPF6DHrD4AwxBbThmmK4QACjmPOmlBQzgMwRO4Uf19Iyh2waK0FB74mpURxj5zKETRYqkNp7evZ+TOpdbN/xBYgBMjM6JdW5gXGYHJbmaBsxVzSpXjvup4XK7fRlYgzzU4+vdp+b4/s8/JFYwP8Wnx6377i6XWoLbfsyhmNg+Vd6TWL17ng5CdQWAH9w02blV3yuyitae/t2EQxB/VuNrL66MoCkTKMW4AlmCuZhL4LOz7acVuaiipHGASc7oY2cmolnWgrln9JeXVfiEV4/HRbmcShc3fN53Y57rydrJBoNvAnmN7iOAT5X87IECCxeslERDtnEDfhtmbzTM=
  - secure: rCzIpAicjXwUKFmYlbFFg9M3zWjw62IZ5TIGhVBfvqhMenmbxXKLNC/F942DP2WP+Bxg3Zf5Q0UxlOWmLDYg5ZPyzvtCOpjjajLphD2EK5FJrrh9R/pjctUsOCV6A1m9LzVmDHNSsjNpZ7K6XSMWfMVh59tUORJM/VMzhhMGdfmPzxAvrHLQLbvU7G/HyPbwrPdlwFfUcWb0k1pR1xlGNSquFpUCEMPdDkTc5T56/B2vYzO0y77yYdKqcYOGY6o4j/hUBAJKb3VJdCfeydHbFp3h5I+5Qk1WEjXFN0jzjOMggMkaWCj5igxlvibe71vH1Rur2uHjTjtlWUbwLJXbwiubrUwYINMiD9vMer2wEcJwsh8RtVJU+SobHt31AQTc77jqI+wbSWWEjAWdCDU8kg33lFnHteLavCG9nbbmfgQyliCN0eLMw7eUSklmD0niabKLPTcR2SdVe/JM0AyCgFsbiK4KCnPDiQKSxJU9MzgGXSjn0Mzh2b/Vsl/JJleMlOOy8G8bjw6xSe+52Ru9sfFtfwufs9VpSXpkdpFYH/hfHyPuPnHhijidWitlQTm15nE9wfJWfQbnIhiRGjrAyguEZ4269Xms85eZhLltA9vXH3V0hHv8iF8HtTiUAo1AourZ/SBicCQ+Oh3BnX6GWdlSGVPL8QVsBw+tXU9Za4U=
